### ISSUE TITLE
Intercept Adjustment - Code bug?

### ISSUE THREAD

**Issue by josephknho** [resplab/predtools#6]
The calibration plot for the recalibrated validation data when plot alone does not appear to match with the calibration plot with it is plot on top of the development data using group = "method"

I believe it could be an issue with the decile grouping? There are 10 deciles in the standalone plot but 9 (one without CI) in the stacked plot.

Also there seems to be a typo for primitive spelled as "premitive" in the plot title

Cheers,
Joseph

**Comment by aminadibi** [comment]
@sephhoe  can you provide a reproducible example with code?

**Comment by josephknho** [comment]
[image: image.png]

**Comment by josephknho** [comment]
![unnamed](https://u
![unnamed](https://user-images.githubusercontent.com/101285251/178071917-fbd15cfc-3431-4ff6-ab0c-9310420630a4.png)
ser-images.githubusercontent.com/101285251/178071904-047f810c-2a29-4975-8c86-f0efdf38dd07.png)

**Comment by josephknho** [comment]
![unnamed](https://user-images.githubusercontent.com/101285251/178071949-aa515d1b-d069-4b5b-b9b7-8b597a2f2a40.png)

**Comment by aminadibi** [comment]
The problem is right in the vignette. @ab-sa  can you take a look?

**Comment by josephknho** [comment]
[image: image.png]
